apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eks-2

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: docker.io/achalpadol/nginx-go:latest

          ports:
            - containerPort: 8000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app2-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app2-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app2-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app2-config
                  key: DB_USER

          volumeMounts:
            - name: db-password
              mountPath: /run/secrets
              readOnly: true

      volumes:
        - name: db-password
          secret:
            secretName: db-secret
