apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: eks-2
spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: db
          image: mariadb:10-focal

          ports:
            - containerPort: 3306

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app1-config
                  key: DB_HOST

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password

        
